// <auto-generated />
using System;
using DAL.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(BookstoreContext))]
    partial class BookstoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("DAL.Model.Classes.Book", b =>
                {
                    b.Property<Guid>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("book_id");

                    b.Property<string>("Author")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("author");

                    b.Property<string>("Genre")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("genre");

                    b.Property<string>("ISBN")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT")
                        .HasColumnName("isbn");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isDeleted");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("BookID");

                    b.ToTable("book");
                });

            modelBuilder.Entity("DAL.Model.Classes.UserAccount", b =>
                {
                    b.Property<Guid>("UserAccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_account_id");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isDeleted");

                    b.Property<string>("Password")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("UserAccountID");

                    b.ToTable("user_account");
                });
#pragma warning restore 612, 618
        }
    }
}
